### ISSUE TITLE
Duplicated class name

### ISSUE THREAD

**Issue by xmoroccan** [OpenIMW/laravel-meta#3]
Without a test, just my linter found it there is a duplicated class at https://github.com/OpenIMW/laravel-meta/blob/a3e093bb0466d92ddadb1d8c4e3c93ee56f2e764/src/Cache.php#L1-L7

import Laravel Cache as some name other than the class itself.

**Comment by melbahja** [comment]
Now fixed I didn't write tests or test cache yet :disappointed:

**Comment by xmoroccan** [comment]
I'll take care of test bruh, just continue your work 🙏
